import type { Locale } from '@/app/[locale]/dictionaries'

/**
 * Localised mountain-range names. Source of truth uses the English label
 * stored in data/destinations.json (e.g. "French Alps"). This avoids showing
 * "French Alps" inside a French or Portuguese page.
 */
const REGIONS: Record<string, Record<Locale, string>> = {
  'French Alps': {
    en: 'French Alps',
    fr: 'Alpes françaises',
    es: 'Alpes franceses',
    pt: 'Alpes franceses',
    it: 'Alpi francesi',
  },
  'Swiss Alps': {
    en: 'Swiss Alps',
    fr: 'Alpes suisses',
    es: 'Alpes suizos',
    pt: 'Alpes suíços',
    it: 'Alpi svizzere',
  },
  'Austrian Alps': {
    en: 'Austrian Alps',
    fr: 'Alpes autrichiennes',
    es: 'Alpes austriacos',
    pt: 'Alpes austríacos',
    it: 'Alpi austriache',
  },
  'Italian Alps': {
    en: 'Italian Alps',
    fr: 'Alpes italiennes',
    es: 'Alpes italianos',
    pt: 'Alpes italianos',
    it: 'Alpi italiane',
  },
  'Spanish Pyrenees': {
    en: 'Spanish Pyrenees',
    fr: 'Pyrénées espagnoles',
    es: 'Pirineos españoles',
    pt: 'Pirenéus espanhóis',
    it: 'Pirenei spagnoli',
  },
  'French Pyrenees': {
    en: 'French Pyrenees',
    fr: 'Pyrénées françaises',
    es: 'Pirineos franceses',
    pt: 'Pirenéus franceses',
    it: 'Pirenei francesi',
  },
  Vosges: {
    en: 'Vosges',
    fr: 'Vosges',
    es: 'Vosgos',
    pt: 'Vosgos',
    it: 'Vosgi',
  },
  Jura: {
    en: 'Jura',
    fr: 'Jura',
    es: 'Jura',
    pt: 'Jura',
    it: 'Giura',
  },
  'Massif Central': {
    en: 'Massif Central',
    fr: 'Massif central',
    es: 'Macizo Central',
    pt: 'Maciço Central',
    it: 'Massiccio Centrale',
  },
  'Andorran Pyrenees': {
    en: 'Andorran Pyrenees',
    fr: 'Pyrénées andorranes',
    es: 'Pirineos andorranos',
    pt: 'Pirenéus andorranos',
    it: 'Pirenei andorrani',
  },
  'Bavarian Alps': {
    en: 'Bavarian Alps',
    fr: 'Alpes bavaroises',
    es: 'Alpes bávaros',
    pt: 'Alpes bávaros',
    it: 'Alpi bavaresi',
  },
  'Black Forest': {
    en: 'Black Forest',
    fr: 'Forêt-Noire',
    es: 'Selva Negra',
    pt: 'Floresta Negra',
    it: 'Foresta Nera',
  },
  'Bavarian Forest': {
    en: 'Bavarian Forest',
    fr: 'Forêt bavaroise',
    es: 'Selva Bávara',
    pt: 'Floresta Bávara',
    it: 'Foresta Bavarese',
  },
  'Norwegian Mountains': {
    en: 'Norwegian Mountains',
    fr: 'Montagnes norvégiennes',
    es: 'Montañas noruegas',
    pt: 'Montanhas norueguesas',
    it: 'Montagne norvegesi',
  },
  'Swedish Mountains': {
    en: 'Swedish Mountains',
    fr: 'Montagnes suédoises',
    es: 'Montañas suecas',
    pt: 'Montanhas suecas',
    it: 'Montagne svedesi',
  },
  'Finnish Lapland': {
    en: 'Finnish Lapland',
    fr: 'Laponie finlandaise',
    es: 'Laponia finlandesa',
    pt: 'Lapónia finlandesa',
    it: 'Lapponia finlandese',
  },
  'Hokkaido': {
    en: 'Hokkaido',
    fr: 'Hokkaidō',
    es: 'Hokkaidō',
    pt: 'Hokkaidō',
    it: 'Hokkaidō',
  },
  'Japanese Alps': {
    en: 'Japanese Alps',
    fr: 'Alpes japonaises',
    es: 'Alpes japoneses',
    pt: 'Alpes japoneses',
    it: 'Alpi giapponesi',
  },
  'Tohoku Mountains': {
    en: 'Tohoku Mountains',
    fr: 'Montagnes du Tōhoku',
    es: 'Montañas de Tōhoku',
    pt: 'Montanhas de Tōhoku',
    it: 'Monti del Tōhoku',
  },
  'Colorado Rockies': {
    en: 'Colorado Rockies',
    fr: 'Rocheuses du Colorado',
    es: 'Rocosas de Colorado',
    pt: 'Rochosas do Colorado',
    it: 'Montagne Rocciose del Colorado',
  },
  'Wasatch Mountains': {
    en: 'Wasatch Mountains',
    fr: 'Montagnes Wasatch',
    es: 'Montañas Wasatch',
    pt: 'Montanhas Wasatch',
    it: 'Monti Wasatch',
  },
  'Sierra Nevada': {
    en: 'Sierra Nevada (California)',
    fr: 'Sierra Nevada (Californie)',
    es: 'Sierra Nevada (California)',
    pt: 'Sierra Nevada (Califórnia)',
    it: 'Sierra Nevada (California)',
  },
  'Northern Rockies': {
    en: 'Northern Rockies',
    fr: 'Rocheuses du Nord',
    es: 'Rocosas del Norte',
    pt: 'Rochosas do Norte',
    it: 'Montagne Rocciose del Nord',
  },
  'Green Mountains': {
    en: 'Green Mountains',
    fr: 'Green Mountains',
    es: 'Green Mountains',
    pt: 'Green Mountains',
    it: 'Green Mountains',
  },
  'Sangre de Cristo': {
    en: 'Sangre de Cristo',
    fr: 'Sangre de Cristo',
    es: 'Sangre de Cristo',
    pt: 'Sangre de Cristo',
    it: 'Sangre de Cristo',
  },
  'Moroccan Atlas': {
    en: 'Moroccan Atlas',
    fr: 'Atlas marocain',
    es: 'Atlas marroquí',
    pt: 'Atlas marroquino',
    it: 'Atlante marocchino',
  },
  'Algerian Mountains': {
    en: 'Algerian Mountains',
    fr: 'Montagnes algériennes',
    es: 'Montañas argelinas',
    pt: 'Montanhas argelinas',
    it: 'Monti algerini',
  },
  'Maluti and Drakensberg': {
    en: 'Maluti and Drakensberg',
    fr: 'Maluti et Drakensberg',
    es: 'Maluti y Drakensberg',
    pt: 'Maluti e Drakensberg',
    it: 'Maluti e Drakensberg',
  },
  'Cairo Indoor': {
    en: 'Cairo Indoor',
    fr: 'Indoor du Caire',
    es: 'Cubierto de El Cairo',
    pt: 'Indoor do Cairo',
    it: 'Indoor del Cairo',
  },
  'Coast Mountains': {
    en: 'Coast Mountains',
    fr: 'Chaîne Côtière',
    es: 'Cordillera Costera',
    pt: 'Cordilheira Costeira',
    it: 'Catena Costiera',
  },
  'Canadian Rockies': {
    en: 'Canadian Rockies',
    fr: 'Rocheuses canadiennes',
    es: 'Rocosas canadienses',
    pt: 'Rochosas canadianas',
    it: 'Montagne Rocciose canadesi',
  },
  'BC Interior': {
    en: 'BC Interior',
    fr: "Intérieur de la Colombie-Britannique",
    es: 'Interior de la Columbia Británica',
    pt: 'Interior da Colúmbia Britânica',
    it: 'Interno della Columbia Britannica',
  },
  'Laurentides': {
    en: 'Laurentides',
    fr: 'Laurentides',
    es: 'Laurentides',
    pt: 'Laurentides',
    it: 'Laurentides',
  },
  'Taebaek Mountains': {
    en: 'Taebaek Mountains',
    fr: 'Monts Taebaek',
    es: 'Montañas Taebaek',
    pt: 'Montanhas Taebaek',
    it: 'Monti Taebaek',
  },
  'Seoul Capital Area': {
    en: 'Seoul Capital Area',
    fr: 'Région métropolitaine de Séoul',
    es: 'Área Metropolitana de Seúl',
    pt: 'Área Metropolitana de Seul',
    it: 'Area metropolitana di Seoul',
  },
  'Sobaek Mountains': {
    en: 'Sobaek Mountains',
    fr: 'Monts Sobaek',
    es: 'Montañas Sobaek',
    pt: 'Montanhas Sobaek',
    it: 'Monti Sobaek',
  },
  'Australian Alps': {
    en: 'Australian Alps',
    fr: 'Alpes australiennes',
    es: 'Alpes australianos',
    pt: 'Alpes australianos',
    it: 'Alpi australiane',
  },
  'Southern Alps': {
    en: 'Southern Alps (NZ)',
    fr: 'Alpes du Sud (Nouvelle-Zélande)',
    es: 'Alpes del Sur (Nueva Zelanda)',
    pt: 'Alpes do Sul (Nova Zelândia)',
    it: 'Alpi del Sud (Nuova Zelanda)',
  },
  'Andes': {
    en: 'Andes',
    fr: 'Andes',
    es: 'Andes',
    pt: 'Andes',
    it: 'Ande',
  },
}

export function localizeRegion(englishName: string, locale: Locale): string {
  return REGIONS[englishName]?.[locale] ?? englishName
}
