import type { Locale } from '@/app/[locale]/dictionaries'

/**
 * Localised mountain-range names. Source of truth uses the English label
 * stored in data/destinations.json (e.g. "French Alps"). This avoids showing
 * "French Alps" inside a French or Portuguese page.
 */
const REGIONS: Record<string, Record<Locale, string>> = {
  'French Alps': {
    en: 'French Alps',
    fr: 'Alpes françaises',
    es: 'Alpes franceses',
    pt: 'Alpes franceses',
    it: 'Alpi francesi',
    ja: 'フランスアルプス',
    nl: 'Franse Alpen',
    'zh-hk': '法國阿爾卑斯山',
  },
  'Swiss Alps': {
    en: 'Swiss Alps',
    fr: 'Alpes suisses',
    es: 'Alpes suizos',
    pt: 'Alpes suíços',
    it: 'Alpi svizzere',
    ja: 'スイスアルプス',
    nl: 'Zwitserse Alpen',
    'zh-hk': '瑞士阿爾卑斯山',
  },
  'Austrian Alps': {
    en: 'Austrian Alps',
    fr: 'Alpes autrichiennes',
    es: 'Alpes austriacos',
    pt: 'Alpes austríacos',
    it: 'Alpi austriache',
    ja: 'オーストリアアルプス',
    nl: 'Oostenrijkse Alpen',
    'zh-hk': '奧地利阿爾卑斯山',
  },
  'Italian Alps': {
    en: 'Italian Alps',
    fr: 'Alpes italiennes',
    es: 'Alpes italianos',
    pt: 'Alpes italianos',
    it: 'Alpi italiane',
    ja: 'イタリアアルプス',
    nl: 'Italiaanse Alpen',
    'zh-hk': '意大利阿爾卑斯山',
  },
  Apennines: {
    en: 'Apennines',
    fr: 'Apennins',
    es: 'Apeninos',
    pt: 'Apeninos',
    it: 'Appennini',
    ja: 'アペニン山脈',
    nl: 'Apennijnen',
    'zh-hk': '亞平寧山脈',
  },
  'Spanish Pyrenees': {
    en: 'Spanish Pyrenees',
    fr: 'Pyrénées espagnoles',
    es: 'Pirineos españoles',
    pt: 'Pirenéus espanhóis',
    it: 'Pirenei spagnoli',
    ja: 'スペイン・ピレネー山脈',
    nl: 'Spaanse Pyreneeën',
    'zh-hk': '西班牙比利牛斯山脈',
  },
  'French Pyrenees': {
    en: 'French Pyrenees',
    fr: 'Pyrénées françaises',
    es: 'Pirineos franceses',
    pt: 'Pirenéus franceses',
    it: 'Pirenei francesi',
    ja: 'フランス・ピレネー山脈',
    nl: 'Franse Pyreneeën',
    'zh-hk': '法國比利牛斯山脈',
  },
  Vosges: {
    en: 'Vosges',
    fr: 'Vosges',
    es: 'Vosgos',
    pt: 'Vosgos',
    it: 'Vosgi',
    ja: 'ヴォージュ山脈',
    nl: 'Vogezen',
    'zh-hk': '孚日山脈',
  },
  Jura: {
    en: 'Jura',
    fr: 'Jura',
    es: 'Jura',
    pt: 'Jura',
    it: 'Giura',
    ja: 'ジュラ山脈',
    nl: 'Jura',
    'zh-hk': '侏羅山脈',
  },
  'Massif Central': {
    en: 'Massif Central',
    fr: 'Massif central',
    es: 'Macizo Central',
    pt: 'Maciço Central',
    it: 'Massiccio Centrale',
    ja: '中央山塊',
    nl: 'Centraal Massief',
    'zh-hk': '中央高原',
  },
  Cascades: {
    en: 'Cascades',
    fr: 'Cascades',
    es: 'Cascadas',
    pt: 'Cascades',
    it: 'Cascade',
    ja: 'カスケード山脈',
    nl: 'Cascades',
    'zh-hk': '喀斯喀特山脈',
  },
  Appalachians: {
    en: 'Appalachians',
    fr: 'Appalaches',
    es: 'Apalaches',
    pt: 'Apalaches',
    it: 'Appalachi',
    ja: 'アパラチア山脈',
    nl: 'Appalachen',
    'zh-hk': '阿巴拉契亞山脈',
  },
  Pirin: {
    en: 'Pirin Mountains',
    fr: 'Pirin',
    es: 'Montes Pirin',
    pt: 'Montes Pirin',
    it: 'Monti Pirin',
    ja: 'ピリン山脈',
    nl: 'Piringebergte',
    'zh-hk': '皮林山脈',
  },
  Rila: {
    en: 'Rila Mountains',
    fr: 'Rila',
    es: 'Montes Rila',
    pt: 'Montes Rila',
    it: 'Monti Rila',
    ja: 'リラ山脈',
    nl: 'Rilagebergte',
    'zh-hk': '里拉山脈',
  },
  'Rhodope Mountains': {
    en: 'Rhodope Mountains',
    fr: 'Rhodopes',
    es: 'Montes Ródope',
    pt: 'Montes Ródope',
    it: 'Monti Rodope',
    ja: 'ロドピ山脈',
    nl: 'Rhodopegebergte',
    'zh-hk': '羅多彼山脈',
  },
  'Andorran Pyrenees': {
    en: 'Andorran Pyrenees',
    fr: 'Pyrénées andorranes',
    es: 'Pirineos andorranos',
    pt: 'Pirenéus andorranos',
    it: 'Pirenei andorrani',
    ja: 'アンドラ・ピレネー山脈',
    nl: 'Andorrese Pyreneeën',
    'zh-hk': '安道爾比利牛斯山脈',
  },
  'Sierra Nevada (Spain)': {
    en: 'Sierra Nevada (Spain)',
    fr: 'Sierra Nevada (Espagne)',
    es: 'Sierra Nevada (España)',
    pt: 'Sierra Nevada (Espanha)',
    it: 'Sierra Nevada (Spagna)',
    ja: 'シエラネバダ（スペイン）',
    nl: 'Sierra Nevada (Spanje)',
    'zh-hk': '內華達山脈（西班牙）',
  },
  'Cantabrian Mountains': {
    en: 'Cantabrian Mountains',
    fr: 'Monts Cantabriques',
    es: 'Cordillera Cantábrica',
    pt: 'Cordilheira Cantábrica',
    it: 'Monti Cantabrici',
    ja: 'カンタブリア山脈',
    nl: 'Cantabrisch Gebergte',
    'zh-hk': '坎塔布里亞山脈',
  },
  'Bavarian Alps': {
    en: 'Bavarian Alps',
    fr: 'Alpes bavaroises',
    es: 'Alpes bávaros',
    pt: 'Alpes bávaros',
    it: 'Alpi bavaresi',
    ja: 'バイエルンアルプス',
    nl: 'Beierse Alpen',
    'zh-hk': '巴伐利亞阿爾卑斯山',
  },
  'Black Forest': {
    en: 'Black Forest',
    fr: 'Forêt-Noire',
    es: 'Selva Negra',
    pt: 'Floresta Negra',
    it: 'Foresta Nera',
    ja: '黒い森',
    nl: 'Zwarte Woud',
    'zh-hk': '黑森林',
  },
  'Bavarian Forest': {
    en: 'Bavarian Forest',
    fr: 'Forêt bavaroise',
    es: 'Selva Bávara',
    pt: 'Floresta Bávara',
    it: 'Foresta Bavarese',
    ja: 'バイエルンの森',
    nl: 'Beierse Woud',
    'zh-hk': '巴伐利亞森林',
  },
  'Norwegian Mountains': {
    en: 'Norwegian Mountains',
    fr: 'Montagnes norvégiennes',
    es: 'Montañas noruegas',
    pt: 'Montanhas norueguesas',
    it: 'Montagne norvegesi',
    ja: 'ノルウェーの山々',
    nl: 'Noorse Bergen',
    'zh-hk': '挪威山脈',
  },
  'Swedish Mountains': {
    en: 'Swedish Mountains',
    fr: 'Montagnes suédoises',
    es: 'Montañas suecas',
    pt: 'Montanhas suecas',
    it: 'Montagne svedesi',
    ja: 'スウェーデンの山々',
    nl: 'Zweedse Bergen',
    'zh-hk': '瑞典山脈',
  },
  'Finnish Lapland': {
    en: 'Finnish Lapland',
    fr: 'Laponie finlandaise',
    es: 'Laponia finlandesa',
    pt: 'Lapónia finlandesa',
    it: 'Lapponia finlandese',
    ja: 'フィンランドのラップランド',
    nl: 'Fins Lapland',
    'zh-hk': '芬蘭拉普蘭',
  },
  'Hokkaido': {
    en: 'Hokkaido',
    fr: 'Hokkaidō',
    es: 'Hokkaidō',
    pt: 'Hokkaidō',
    it: 'Hokkaidō',
    ja: '北海道',
    nl: 'Hokkaidō',
    'zh-hk': '北海道',
  },
  'Japanese Alps': {
    en: 'Japanese Alps',
    fr: 'Alpes japonaises',
    es: 'Alpes japoneses',
    pt: 'Alpes japoneses',
    it: 'Alpi giapponesi',
    ja: '日本アルプス',
    nl: 'Japanse Alpen',
    'zh-hk': '日本阿爾卑斯山',
  },
  'Tohoku Mountains': {
    en: 'Tohoku Mountains',
    fr: 'Montagnes du Tōhoku',
    es: 'Montañas de Tōhoku',
    pt: 'Montanhas de Tōhoku',
    it: 'Monti del Tōhoku',
    ja: '東北山地',
    nl: 'Tōhoku-gebergte',
    'zh-hk': '東北山地',
  },
  'Colorado Rockies': {
    en: 'Colorado Rockies',
    fr: 'Rocheuses du Colorado',
    es: 'Rocosas de Colorado',
    pt: 'Rochosas do Colorado',
    it: 'Montagne Rocciose del Colorado',
    ja: 'コロラド・ロッキー山脈',
    nl: 'Rotsgebergte van Colorado',
    'zh-hk': '科羅拉多洛磯山脈',
  },
  'Wasatch Mountains': {
    en: 'Wasatch Mountains',
    fr: 'Montagnes Wasatch',
    es: 'Montañas Wasatch',
    pt: 'Montanhas Wasatch',
    it: 'Monti Wasatch',
    ja: 'ワサッチ山脈',
    nl: 'Wasatchgebergte',
    'zh-hk': '瓦薩奇山脈',
  },
  'Sierra Nevada': {
    en: 'Sierra Nevada (California)',
    fr: 'Sierra Nevada (Californie)',
    es: 'Sierra Nevada (California)',
    pt: 'Sierra Nevada (Califórnia)',
    it: 'Sierra Nevada (California)',
    ja: 'シエラネバダ（カリフォルニア）',
    nl: 'Sierra Nevada (Californië)',
    'zh-hk': '內華達山脈（加州）',
  },
  'Northern Rockies': {
    en: 'Northern Rockies',
    fr: 'Rocheuses du Nord',
    es: 'Rocosas del Norte',
    pt: 'Rochosas do Norte',
    it: 'Montagne Rocciose del Nord',
    ja: '北ロッキー山脈',
    nl: 'Noordelijk Rotsgebergte',
    'zh-hk': '北洛磯山脈',
  },
  'Green Mountains': {
    en: 'Green Mountains',
    fr: 'Green Mountains',
    es: 'Green Mountains',
    pt: 'Green Mountains',
    it: 'Green Mountains',
    ja: 'Green Mountains',
    nl: 'Green Mountains',
    'zh-hk': 'Green Mountains',
  },
  'Sangre de Cristo': {
    en: 'Sangre de Cristo',
    fr: 'Sangre de Cristo',
    es: 'Sangre de Cristo',
    pt: 'Sangre de Cristo',
    it: 'Sangre de Cristo',
    ja: 'Sangre de Cristo',
    nl: 'Sangre de Cristo',
    'zh-hk': 'Sangre de Cristo',
  },
  'Moroccan Atlas': {
    en: 'Moroccan Atlas',
    fr: 'Atlas marocain',
    es: 'Atlas marroquí',
    pt: 'Atlas marroquino',
    it: 'Atlante marocchino',
    ja: 'モロッコ・アトラス山脈',
    nl: 'Marokkaanse Atlas',
    'zh-hk': '摩洛哥阿特拉斯山脈',
  },
  'Algerian Mountains': {
    en: 'Algerian Mountains',
    fr: 'Montagnes algériennes',
    es: 'Montañas argelinas',
    pt: 'Montanhas argelinas',
    it: 'Monti algerini',
    ja: 'アルジェリアの山々',
    nl: 'Algerijnse bergen',
    'zh-hk': '阿爾及利亞山脈',
  },
  'Maluti and Drakensberg': {
    en: 'Maluti and Drakensberg',
    fr: 'Maluti et Drakensberg',
    es: 'Maluti y Drakensberg',
    pt: 'Maluti e Drakensberg',
    it: 'Maluti e Drakensberg',
    ja: 'マルーティとドラケンスバーグ',
    nl: 'Maluti en Drakensberg',
    'zh-hk': '馬盧蒂與德拉肯斯堡',
  },
  'Cairo Indoor': {
    en: 'Cairo Indoor',
    fr: 'Indoor du Caire',
    es: 'Cubierto de El Cairo',
    pt: 'Indoor do Cairo',
    it: 'Indoor del Cairo',
    ja: 'カイロ・インドア',
    nl: 'Indoor Caïro',
    'zh-hk': '開羅室內',
  },
  'Coast Mountains': {
    en: 'Coast Mountains',
    fr: 'Chaîne Côtière',
    es: 'Cordillera Costera',
    pt: 'Cordilheira Costeira',
    it: 'Catena Costiera',
    ja: '海岸山脈',
    nl: 'Kustgebergte',
    'zh-hk': '海岸山脈',
  },
  'Canadian Rockies': {
    en: 'Canadian Rockies',
    fr: 'Rocheuses canadiennes',
    es: 'Rocosas canadienses',
    pt: 'Rochosas canadianas',
    it: 'Montagne Rocciose canadesi',
    ja: 'カナディアン・ロッキー山脈',
    nl: 'Canadese Rotsgebergte',
    'zh-hk': '加拿大洛磯山脈',
  },
  'BC Interior': {
    en: 'BC Interior',
    fr: "Intérieur de la Colombie-Britannique",
    es: 'Interior de la Columbia Británica',
    pt: 'Interior da Colúmbia Britânica',
    it: 'Interno della Columbia Britannica',
    ja: 'ブリティッシュコロンビア内陸部',
    nl: 'Binnenland van Brits-Columbia',
    'zh-hk': '卑詩省內陸',
  },
  'Laurentides': {
    en: 'Laurentides',
    fr: 'Laurentides',
    es: 'Laurentides',
    pt: 'Laurentides',
    it: 'Laurentides',
    ja: 'Laurentides',
    nl: 'Laurentides',
    'zh-hk': 'Laurentides',
  },
  'Taebaek Mountains': {
    en: 'Taebaek Mountains',
    fr: 'Monts Taebaek',
    es: 'Montañas Taebaek',
    pt: 'Montanhas Taebaek',
    it: 'Monti Taebaek',
    ja: 'テベク山脈',
    nl: 'Taebaekgebergte',
    'zh-hk': '太白山脈',
  },
  'Seoul Capital Area': {
    en: 'Seoul Capital Area',
    fr: 'Région métropolitaine de Séoul',
    es: 'Área Metropolitana de Seúl',
    pt: 'Área Metropolitana de Seul',
    it: 'Area metropolitana di Seoul',
    ja: 'ソウル首都圏',
    nl: 'Metropoolregio Seoel',
    'zh-hk': '首爾首都圈',
  },
  'Sobaek Mountains': {
    en: 'Sobaek Mountains',
    fr: 'Monts Sobaek',
    es: 'Montañas Sobaek',
    pt: 'Montanhas Sobaek',
    it: 'Monti Sobaek',
    ja: 'ソベク山脈',
    nl: 'Sobaekgebergte',
    'zh-hk': '小白山脈',
  },
  'Australian Alps': {
    en: 'Australian Alps',
    fr: 'Alpes australiennes',
    es: 'Alpes australianos',
    pt: 'Alpes australianos',
    it: 'Alpi australiane',
    ja: 'オーストラリアンアルプス',
    nl: 'Australische Alpen',
    'zh-hk': '澳洲阿爾卑斯山',
  },
  'Southern Alps': {
    en: 'Southern Alps (NZ)',
    fr: 'Alpes du Sud (Nouvelle-Zélande)',
    es: 'Alpes del Sur (Nueva Zelanda)',
    pt: 'Alpes do Sul (Nova Zelândia)',
    it: 'Alpi del Sud (Nuova Zelanda)',
    ja: 'サザンアルプス（ニュージーランド）',
    nl: 'Zuidelijke Alpen (Nieuw-Zeeland)',
    'zh-hk': '南阿爾卑斯山（紐西蘭）',
  },
  'Andes': {
    en: 'Andes',
    fr: 'Andes',
    es: 'Andes',
    pt: 'Andes',
    it: 'Ande',
    ja: 'アンデス山脈',
    nl: 'Andes',
    'zh-hk': '安第斯山脈',
  },
}

export function localizeRegion(englishName: string, locale: Locale): string {
  return REGIONS[englishName]?.[locale] ?? englishName
}
