/**
 * Official resort websites, keyed by destination slug.
 *
 * Best-effort official tourism / ski-area domains, correct as of the 2026 season.
 * Verify before launch: a handful of resorts occasionally migrate domains.
 *
 * Ski-rental and lift-pass links are generated dynamically from the resort name
 * and coordinates (Google Maps searches), so they never go stale, see lib below.
 */
const RESORT_SITES: Record<string, string> = {
  'val-thorens': 'https://www.valthorens.com',
  'val-d-isere': 'https://www.valdisere.com',
  courchevel: 'https://www.courchevel.com',
  meribel: 'https://www.meribel.net',
  chamonix: 'https://www.chamonix.com',
  'les-arcs': 'https://www.lesarcs.com',
  'la-plagne': 'https://www.la-plagne.com',
  tignes: 'https://www.tignes.net',
  'alpe-d-huez': 'https://www.alpedhuez.com',
  'serre-chevalier': 'https://www.serre-chevalier.com',
  zermatt: 'https://www.zermatt.ch',
  verbier: 'https://www.verbier.ch',
  'st-moritz': 'https://www.stmoritz.com',
  'crans-montana': 'https://www.crans-montana.ch',
  'saas-fee': 'https://www.saas-fee.ch',
  davos: 'https://www.davos.ch',
  andermatt: 'https://www.andermatt.ch',
  'st-anton': 'https://www.stantonamarlberg.com',
  ischgl: 'https://www.ischgl.com',
  solden: 'https://www.soelden.com',
  mayrhofen: 'https://www.mayrhofen.at',
  kitzbuhel: 'https://www.kitzbuehel.com',
  saalbach: 'https://www.saalbach.com',
  'lech-zurs': 'https://www.lechzuers.com',
  obergurgl: 'https://www.obergurgl.com',
  'cortina-d-ampezzo': 'https://www.cortinadolomiti.eu',
  livigno: 'https://www.livigno.eu',
  cervinia: 'https://www.cervinia.it',
  'madonna-di-campiglio': 'https://www.campigliodolomiti.it',
  sestriere: 'https://www.vialattea.it',
  'selva-val-gardena': 'https://www.valgardena.it',
  'baqueira-beret': 'https://www.baqueira.es',
  formigal: 'https://www.formigal-panticosa.com',
  cerler: 'https://www.cerler.com',
  grandvalira: 'https://www.grandvalira.com',
  'vallnord-pal-arinsal': 'https://www.pal-arinsal.com',
  'saint-lary': 'https://www.saintlary.com',
  peyragudes: 'https://www.peyragudes.com',
  'font-romeu': 'https://www.font-romeu.fr',
  'grand-tourmalet': 'https://www.grand-tourmalet.com',
  cauterets: 'https://www.cauterets.com',
  'les-menuires': 'https://www.lesmenuires.com',
  avoriaz: 'https://www.avoriaz.com',
  morzine: 'https://www.morzine-avoriaz.com',
  'les-gets': 'https://www.lesgets.com',
  megeve: 'https://www.megeve.com',
  'la-clusaz': 'https://www.laclusaz.com',
  'les-deux-alpes': 'https://www.les2alpes.com',
  'la-rosiere': 'https://www.larosiere.net',
  flaine: 'https://www.flaine.com',
  samoens: 'https://www.samoens.com',
  chatel: 'https://www.chatel.com',
  valmorel: 'https://www.valmorel.com',
  montgenevre: 'https://www.montgenevre.com',
  'les-saisies': 'https://www.lessaisies.com',
  'le-grand-bornand': 'https://www.legrandbornand.com',
  'sainte-foy-tarentaise': 'https://www.saintefoy-tarentaise.com',
  'val-cenis': 'https://www.valcenis.com',
  vaujany: 'https://www.vaujany.com',
  risoul: 'https://www.risoul.com',
  vars: 'https://www.vars.com',
  'pra-loup': 'https://www.praloup.com',
  'isola-2000': 'https://www.isola2000.com',
  'saint-gervais': 'https://www.saintgervais.com',
  'ax-3-domaines': 'https://www.ax-ski.com',
  'les-angles': 'https://www.lesangles.com',
  candanchu: 'https://www.candanchu.com',
  'la-molina': 'https://www.lamolina.cat',
  'les-sybelles': 'https://www.sybelles.ski',
  valloire: 'https://www.valloire.com',
  'orcieres-merlette': 'https://www.orcieres.com',
  'les-orres': 'https://www.lesorres.com',
  auron: 'https://www.auron.com',
  'les-contamines': 'https://www.lescontamines.com',
  'piau-engaly': 'https://www.piau-engaly.com',
  'luz-ardiden': 'https://www.luz-ardiden.com',
  gourette: 'https://www.gourette.com',
  astun: 'https://www.astun.com',
  'boi-taull': 'https://www.boitaull.com',
  'vallnord-ordino-arcalis': 'https://www.ordinoarcalis.com',
  'bonneval-sur-arc': 'https://www.bonneval-sur-arc.com',
  superdevoluy: 'https://www.ledevoluy.com',
  valberg: 'https://www.valberg.com',
  chamrousse: 'https://www.chamrousse.com',
  combloux: 'https://www.combloux.com',
  valfrejus: 'https://www.valfrejus.com',
  'la-pierre-saint-martin': 'https://www.lapierrestmartin.com',
  guzet: 'https://www.guzet.com',
  'porte-puymorens': 'https://www.porte-puymorens.fr',
  masella: 'https://www.masella.com',
  panticosa: 'https://www.formigal-panticosa.com',
  'port-aine': 'https://www.port-aine.com',
  'les-7-laux': 'https://www.les7laux.com',
  'villard-de-lans': 'https://www.villarddelans.com',
  'saint-francois-longchamp': 'https://www.saintfrancoislongchamp.com',
  aussois: 'https://www.aussois.com',
  valmeinier: 'https://www.valmeinier.com',
  'areches-beaufort': 'https://www.areches-beaufort.com',
  'la-norma': 'https://www.la-norma.com',
  'les-houches': 'https://www.leshouches.com',
  'luchon-superbagneres': 'https://www.luchon-superbagneres.com',
  formigueres: 'https://www.formigueres.fr',
  'val-louron': 'https://www.vallouron.com',
  espot: 'https://www.espotesqui.cat',
  'vallter-2000': 'https://www.vallter.cat',
  'port-del-comte': 'https://www.portdelcomte.net',
  grindelwald: 'https://www.grindelwald.swiss',
  wengen: 'https://www.wengen.swiss',
  murren: 'https://www.muerren.swiss',
  engelberg: 'https://www.engelberg.ch',
  laax: 'https://www.laax.com',
  'arosa-lenzerheide': 'https://arosalenzerheide.swiss',
  nendaz: 'https://www.nendaz.ch',
  veysonnaz: 'https://www.veysonnaz.ch',
  'villars-gryon': 'https://www.villars.ch',
  'les-diablerets': 'https://www.diablerets.ch',
  adelboden: 'https://www.adelboden.ch',
  gstaad: 'https://www.gstaad.ch',
  champery: 'https://www.champery.ch',
  'grimentz-zinal': 'https://www.valdanniviers.ch',
  obertauern: 'https://www.obertauern.com',
  schladming: 'https://www.schladming-dachstein.at',
  'bad-gastein': 'https://www.gastein.com',
  'bad-hofgastein': 'https://www.gastein.com',
  'zell-am-see': 'https://www.zellamsee-kaprun.com',
  kaprun: 'https://www.zellamsee-kaprun.com',
  hintertux: 'https://www.hintertuxergletscher.at',
  'serfaus-fiss-ladis': 'https://www.serfaus-fiss-ladis.at',
  nauders: 'https://www.nauders.com',
  stubai: 'https://www.stubaier-gletscher.com',
  kuhtai: 'https://www.kuehtai.info',
  soll: 'https://www.skiwelt.at',
  alpbach: 'https://www.skijuwel.com',
  fieberbrunn: 'https://www.fieberbrunn.com',
  gerlos: 'https://www.zillertalarena.com',
  flachau: 'https://www.snow-space.com',
  'alta-badia': 'https://www.altabadia.org',
  canazei: 'https://www.fassa.com',
  arabba: 'https://www.arabba.it',
  ortisei: 'https://www.valgardena.it',
  bormio: 'https://www.bormio.eu',
  'la-thuile': 'https://www.lathuile.it',
  courmayeur: 'https://www.courmayeur-mont-blanc.com',
  'sauze-doulx': 'https://www.sauzedoulx.it',
  alagna: 'https://www.alagna.it',
  champoluc: 'https://www.monterosa-ski.com',
  gressoney: 'https://www.monterosa-ski.com',
  kronplatz: 'https://www.kronplatz.com',
  'san-martino-di-castrozza': 'https://www.sanmartino.com',
  pila: 'https://www.pila.it',
  'passo-tonale': 'https://www.pontedilegnotonale.com',
  'folgarida-marilleva': 'https://www.skiareacampiglio.it',
}

export function resortSite(slug: string): string | null {
  return RESORT_SITES[slug] ?? null
}

/** Google Maps search for ski-rental shops in and around the resort. */
export function skiRentalMapsUrl(name: string, country: string): string {
  const q = encodeURIComponent(`ski rental ${name} ${country}`)
  return `https://www.google.com/maps/search/?api=1&query=${q}`
}
