import type { Locale } from '@/app/[locale]/dictionaries'

/**
 * Ski areas (domaines skiables): big linked domains where several of our resorts
 * share one lift pass or massif. These pages group member resorts for internal
 * linking (maillage) and capture domain-level search intent ("Les 3 Vallées
 * hotels", "Portes du Soleil ski-in ski-out", etc.).
 *
 * `members` are destination slugs from data/destinations.json, in display order.
 * `pistesKm` / `lifts` are the authoritative DOMAIN totals (not a sum of members,
 * which would double-count a shared domain). `lat`/`lng` centre the Stay22 map.
 */
export interface SkiArea {
  slug: string
  name: string
  countryCodes: string[]
  flags: string[]
  /** Destination slugs that belong to this domain, in display order. */
  members: string[]
  lat: number
  lng: number
  zoom: number
  /** Authoritative domain total piste kilometres. */
  pistesKm: number
  /** Authoritative domain total lift count. */
  lifts: number
  /** Highest lift-served altitude in the domain, metres. */
  topAltitude: number
  /** Marketing / lift-pass name of the domain. */
  pass: string
  intro: Record<Locale, string>
  description: Record<Locale, string>
}

export const SKI_AREAS: SkiArea[] = [
  {
    slug: 'les-3-vallees',
    name: 'Les 3 Vallées',
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['val-thorens', 'courchevel', 'meribel', 'les-menuires'],
    lat: 45.35,
    lng: 6.58,
    zoom: 11,
    pistesKm: 600,
    lifts: 160,
    topAltitude: 3230,
    pass: 'Les 3 Vallées',
    intro: {
      en: 'The largest linked ski area in the world: 600 km of piste and eight resorts on a single lift pass, high above the Tarentaise.',
      fr: "Le plus grand domaine relié du monde : 600 km de pistes et huit stations sur un seul forfait, tout en haut de la Tarentaise.",
      es: "El mayor dominio enlazado del mundo: 600 km de pistas y ocho estaciones con un solo forfait, en lo alto de la Tarentaise.",
      pt: "O maior domínio ligado do mundo: 600 km de pistas e oito estâncias num só forfait, no alto da Tarentaise.",
    },
    description: {
      en: 'Les 3 Vallées joins Courchevel, Méribel, Val Thorens and Les Menuires, plus their satellites, into one vast 600 km playground served by around 160 lifts, almost all of it above 1800 m. It is the benchmark for big-mountain skiing in France, with terrain for every level and snow that lasts thanks to the altitude. One pass covers four of our resorts, so you can base yourself anywhere and ski the lot.',
      fr: "Les 3 Vallées relient Courchevel, Méribel, Val Thorens et Les Menuires, plus leurs satellites, en un immense terrain de jeu de 600 km desservi par environ 160 remontées, presque tout au-dessus de 1800 m. C'est la référence du grand ski en France, avec du terrain pour tous les niveaux et une neige qui tient grâce à l'altitude. Un seul forfait couvre quatre de nos stations : on peut loger n'importe où et tout skier.",
      es: "Les 3 Vallées une Courchevel, Méribel, Val Thorens y Les Menuires, además de sus satélites, en un inmenso terreno de juego de 600 km servido por unos 160 remontes, casi todo por encima de los 1800 m. Es la referencia del gran esquí en Francia, con terreno para todos los niveles y una nieve que aguanta gracias a la altitud. Un solo forfait cubre cuatro de nuestras estaciones: puedes alojarte donde quieras y esquiarlo todo.",
      pt: "As 3 Vallées unem Courchevel, Méribel, Val Thorens e Les Menuires, mais os seus satélites, num imenso recreio de 600 km servido por cerca de 160 teleféricos, quase tudo acima dos 1800 m. É a referência do grande esqui em França, com terreno para todos os níveis e uma neve que aguenta graças à altitude. Um só forfait cobre quatro das nossas estâncias: pode ficar em qualquer uma e esquiar tudo.",
    },
  },
  {
    slug: 'paradiski',
    name: 'Paradiski',
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['les-arcs', 'la-plagne'],
    lat: 45.55,
    lng: 6.77,
    zoom: 11,
    pistesKm: 425,
    lifts: 130,
    topAltitude: 3250,
    pass: 'Paradiski',
    intro: {
      en: "Les Arcs and La Plagne joined by the double-decker Vanoise Express cable car, 425 km on one pass.",
      fr: "Les Arcs et La Plagne reliés par le téléphérique à deux étages Vanoise Express, 425 km sur un seul forfait.",
      es: "Les Arcs y La Plagne unidos por el teleférico de dos pisos Vanoise Express, 425 km con un solo forfait.",
      pt: "Les Arcs e La Plagne ligados pelo teleférico de dois andares Vanoise Express, 425 km num só forfait.",
    },
    description: {
      en: 'Paradiski links Les Arcs and La Plagne across the Ponturin valley via the Vanoise Express, one of the world\'s largest cable cars, for 425 km of piste topping out on the Bellecôte glacier at 3250 m. It pairs high, snow-sure skiing with a huge spread of slope-side accommodation. Base in either resort and the whole domain is a cable-car ride away.',
      fr: "Paradiski relie Les Arcs et La Plagne par-dessus la vallée du Ponturin grâce au Vanoise Express, l'un des plus grands téléphériques du monde, pour 425 km de pistes culminant sur le glacier de Bellecôte à 3250 m. Il associe un ski d'altitude bien enneigé à une énorme offre d'hébergement au pied des pistes. Logez dans l'une ou l'autre station, tout le domaine est à un téléphérique.",
      es: "Paradiski une Les Arcs y La Plagne por encima del valle del Ponturin mediante el Vanoise Express, uno de los mayores teleféricos del mundo, para 425 km de pistas que culminan en el glaciar de Bellecôte a 3250 m. Combina un esquí de altura con buena nieve y una enorme oferta de alojamiento a pie de pista. Alójate en cualquiera de las dos y todo el dominio queda a un teleférico.",
      pt: "Paradiski liga Les Arcs e La Plagne por cima do vale do Ponturin através do Vanoise Express, um dos maiores teleféricos do mundo, para 425 km de pistas que culminam no glaciar de Bellecôte a 3250 m. Combina um esqui de altitude com boa neve e uma enorme oferta de alojamento no sopé das pistas. Fique numa das duas e todo o domínio está a um teleférico de distância.",
    },
  },
  {
    slug: 'espace-killy',
    name: 'Espace Killy',
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['tignes', 'val-d-isere'],
    lat: 45.45,
    lng: 6.95,
    zoom: 11,
    pistesKm: 300,
    lifts: 78,
    topAltitude: 3456,
    pass: "Tignes-Val d'Isère (Espace Killy)",
    intro: {
      en: "Tignes and Val d'Isère together, 300 km of high, snow-sure piste known to a generation as the Espace Killy.",
      fr: "Tignes et Val d'Isère réunis, 300 km de pistes hautes et bien enneigées, connues d'une génération sous le nom d'Espace Killy.",
      es: "Tignes y Val d'Isère juntos, 300 km de pistas altas y de nieve segura, conocidas por una generación como el Espace Killy.",
      pt: "Tignes e Val d'Isère juntos, 300 km de pistas altas e de neve segura, conhecidas por uma geração como o Espace Killy.",
    },
    description: {
      en: 'The Espace Killy links Tignes and Val d\'Isère into 300 km of mostly high-altitude piste topping out on the Grande Motte glacier at 3456 m, which is why the season here runs longer than almost anywhere in the Alps. It is a serious skier\'s domain, big on vertical, off-piste and reliable snow. Stay in either resort and the lifts carry you seamlessly across both.',
      fr: "L'Espace Killy relie Tignes et Val d'Isère en 300 km de pistes surtout d'altitude, culminant sur le glacier de la Grande Motte à 3456 m, ce qui explique une saison plus longue que presque partout ailleurs dans les Alpes. C'est un domaine de skieurs, généreux en dénivelé, en hors-piste et en neige fiable. Logez dans l'une ou l'autre, les remontées vous font passer de l'une à l'autre sans rupture.",
      es: "El Espace Killy une Tignes y Val d'Isère en 300 km de pistas sobre todo de altura, que culminan en el glaciar de la Grande Motte a 3456 m, lo que explica una temporada más larga que casi en cualquier sitio de los Alpes. Es un dominio de esquiadores, generoso en desnivel, fuera de pista y nieve fiable. Alójate en cualquiera de las dos y los remontes te llevan de una a otra sin cortes.",
      pt: "O Espace Killy liga Tignes e Val d'Isère em 300 km de pistas sobretudo de altitude, que culminam no glaciar da Grande Motte a 3456 m, o que explica uma época mais longa do que quase em qualquer lado dos Alpes. É um domínio de esquiadores, generoso em desnível, fora-de-pista e neve fiável. Fique numa das duas e os teleféricos levam-no de uma à outra sem interrupções.",
    },
  },
  {
    slug: 'portes-du-soleil',
    name: 'Portes du Soleil',
    countryCodes: ['FR', 'CH'],
    flags: ['🇫🇷', '🇨🇭'],
    members: ['avoriaz', 'morzine', 'les-gets', 'chatel'],
    lat: 46.23,
    lng: 6.78,
    zoom: 11,
    pistesKm: 600,
    lifts: 196,
    topAltitude: 2466,
    pass: 'Portes du Soleil',
    intro: {
      en: "One of the world's biggest international domains: around 600 km across a dozen French and Swiss villages on a single pass.",
      fr: "L'un des plus grands domaines internationaux du monde : environ 600 km à travers une douzaine de villages français et suisses sur un seul forfait.",
      es: "Uno de los mayores dominios internacionales del mundo: unos 600 km a través de una docena de pueblos franceses y suizos con un solo forfait.",
      pt: "Um dos maiores domínios internacionais do mundo: cerca de 600 km por uma dúzia de aldeias francesas e suíças num só forfait.",
    },
    description: {
      en: 'The Portes du Soleil strings a dozen resorts across the French and Swiss border into roughly 600 km of piste served by some 196 lifts, all linked ski-to-ski around a great loop. It is mostly intermediate, tree-lined and hugely varied, from family Les Gets to the cliff-top modernism of Avoriaz. Four of its French villages feature here, each a different way into the same vast circuit.',
      fr: "Les Portes du Soleil enchaînent une douzaine de stations de part et d'autre de la frontière franco-suisse en quelque 600 km de pistes desservies par environ 196 remontées, reliées skis aux pieds sur une grande boucle. Le ski y est surtout intermédiaire, boisé et très varié, de la familiale Les Gets au modernisme perché d'Avoriaz. Quatre de ses villages français figurent ici, chacun une porte d'entrée différente vers le même vaste circuit.",
      es: "Los Portes du Soleil encadenan una docena de estaciones a ambos lados de la frontera francosuiza en unos 600 km de pistas servidas por cerca de 196 remontes, enlazadas a pie de pista en un gran circuito. El esquí es sobre todo intermedio, arbolado y muy variado, de la familiar Les Gets al modernismo colgado de Avoriaz. Cuatro de sus pueblos franceses aparecen aquí, cada uno una entrada distinta al mismo vasto circuito.",
      pt: "Os Portes du Soleil encadeiam uma dúzia de estâncias de ambos os lados da fronteira franco-suíça em cerca de 600 km de pistas servidas por uns 196 teleféricos, ligadas a esqui num grande circuito. O esqui é sobretudo intermédio, arborizado e muito variado, da familiar Les Gets ao modernismo empoleirado de Avoriaz. Quatro das suas aldeias francesas aparecem aqui, cada uma uma entrada diferente para o mesmo vasto circuito.",
    },
  },
  {
    slug: 'evasion-mont-blanc',
    name: 'Évasion Mont-Blanc',
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['megeve', 'saint-gervais', 'combloux'],
    lat: 45.86,
    lng: 6.62,
    zoom: 11,
    pistesKm: 400,
    lifts: 100,
    topAltitude: 2350,
    pass: 'Évasion Mont-Blanc',
    intro: {
      en: '400 km of sunny, scenic piste under Mont Blanc, shared by Megève, Saint-Gervais and Combloux.',
      fr: "400 km de pistes ensoleillées et panoramiques sous le Mont Blanc, partagées par Megève, Saint-Gervais et Combloux.",
      es: "400 km de pistas soleadas y panorámicas bajo el Mont Blanc, compartidas por Megève, Saint-Gervais y Combloux.",
      pt: "400 km de pistas solarengas e panorâmicas sob o Mont Blanc, partilhadas por Megève, Saint-Gervais e Combloux.",
    },
    description: {
      en: 'Évasion Mont-Blanc links Megève, Saint-Gervais, Combloux and their neighbours into 400 km of mostly gentle, beautifully scenic piste facing the Mont Blanc massif. It is intermediate heaven, long cruising runs through forest and over open balconies, with the grandest backdrop in the Alps. Pick the chic of Megève or the spa-town calm of Saint-Gervais and ski the lot.',
      fr: "Évasion Mont-Blanc relie Megève, Saint-Gervais, Combloux et leurs voisines en 400 km de pistes surtout douces et magnifiquement panoramiques, face au massif du Mont-Blanc. C'est le paradis des intermédiaires, de longues pistes roulantes en forêt et sur des balcons dégagés, avec le plus grand décor des Alpes. Choisissez le chic de Megève ou le calme thermal de Saint-Gervais, et skiez tout.",
      es: "Évasion Mont-Blanc une Megève, Saint-Gervais, Combloux y sus vecinas en 400 km de pistas sobre todo suaves y de gran belleza, frente al macizo del Mont Blanc. Es el paraíso del intermedio, largas pistas rodadoras por el bosque y sobre balcones abiertos, con el mayor telón de fondo de los Alpes. Elige el chic de Megève o la calma termal de Saint-Gervais y esquíalo todo.",
      pt: "Évasion Mont-Blanc une Megève, Saint-Gervais, Combloux e as suas vizinhas em 400 km de pistas sobretudo suaves e de grande beleza, viradas para o maciço do Mont Blanc. É o paraíso do intermédio, longas pistas roladoras pela floresta e sobre varandas abertas, com o maior pano de fundo dos Alpes. Escolha o chique de Megève ou a calma termal de Saint-Gervais e esquie tudo.",
    },
  },
  {
    slug: 'grand-massif',
    name: 'Grand Massif',
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['flaine', 'samoens'],
    lat: 46.0,
    lng: 6.72,
    zoom: 11,
    pistesKm: 265,
    lifts: 60,
    topAltitude: 2500,
    pass: 'Grand Massif',
    intro: {
      en: '265 km above the Giffre valley, from snow-sure Flaine to the old village of Samoëns.',
      fr: "265 km au-dessus de la vallée du Giffre, de la sûre Flaine au vieux village de Samoëns.",
      es: "265 km sobre el valle del Giffre, de la segura Flaine al viejo pueblo de Samoëns.",
      pt: "265 km acima do vale do Giffre, da segura Flaine à velha aldeia de Samoëns.",
    },
    description: {
      en: 'The Grand Massif links Flaine, Samoëns, Morillon, Les Carroz and Sixt into 265 km of piste, crowned by the snow-sure bowl of Flaine and the long Cascades run down to the valley. It blends a high, purpose-built hub with genuine old Savoyard villages, less than an hour from Geneva. Two of its faces feature here, very different bases for the same domain.',
      fr: "Le Grand Massif relie Flaine, Samoëns, Morillon, Les Carroz et Sixt en 265 km de pistes, couronnés par la combe bien enneigée de Flaine et la longue piste des Cascades jusqu'à la vallée. Il associe un pôle d'altitude construit à de vrais vieux villages savoyards, à moins d'une heure de Genève. Deux de ses visages figurent ici, deux bases très différentes pour le même domaine.",
      es: "El Grand Massif une Flaine, Samoëns, Morillon, Les Carroz y Sixt en 265 km de pistas, coronados por el circo de nieve segura de Flaine y la larga pista de las Cascades hasta el valle. Combina un núcleo de altura construido con auténticos viejos pueblos saboyanos, a menos de una hora de Ginebra. Dos de sus caras aparecen aquí, dos bases muy distintas para el mismo dominio.",
      pt: "O Grand Massif une Flaine, Samoëns, Morillon, Les Carroz e Sixt em 265 km de pistas, coroados pelo circo de neve segura de Flaine e pela longa pista das Cascades até ao vale. Combina um polo de altitude construído com autênticas velhas aldeias saboianas, a menos de uma hora de Genebra. Duas das suas faces aparecem aqui, duas bases muito diferentes para o mesmo domínio.",
    },
  },
  {
    slug: 'foret-blanche',
    name: 'La Forêt Blanche',
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['vars', 'risoul'],
    lat: 44.6,
    lng: 6.67,
    zoom: 12,
    pistesKm: 185,
    lifts: 51,
    topAltitude: 2750,
    pass: 'La Forêt Blanche',
    intro: {
      en: 'Vars and Risoul joined over the ridge, 185 km of sunny southern-Alps piste through the larches.',
      fr: "Vars et Risoul reliés par la crête, 185 km de pistes ensoleillées des Alpes du Sud à travers les mélèzes.",
      es: "Vars y Risoul unidos por la cresta, 185 km de pistas soleadas de los Alpes del Sur entre alerces.",
      pt: "Vars e Risoul ligados pela crista, 185 km de pistas solarengas dos Alpes do Sul por entre lariços.",
    },
    description: {
      en: 'La Forêt Blanche links Vars and Risoul across the Pic de Chabrières into 185 km of sunny, larch-lined piste in the southern Alps. It is friendly, good value and reliably bright, with enough sweeping reds and off-piste to keep strong skiers happy. Base in either resort and the whole domain opens up over the hill.',
      fr: "La Forêt Blanche relie Vars et Risoul par le Pic de Chabrières en 185 km de pistes ensoleillées et bordées de mélèzes, dans les Alpes du Sud. Accueillante, d'un bon rapport qualité-prix et fidèlement lumineuse, elle offre assez de grandes rouges et de hors-piste pour contenter les bons skieurs. Logez dans l'une ou l'autre, tout le domaine s'ouvre de l'autre côté de la crête.",
      es: "La Forêt Blanche une Vars y Risoul por el Pic de Chabrières en 185 km de pistas soleadas y bordeadas de alerces, en los Alpes del Sur. Acogedora, de buena relación calidad-precio y fiablemente luminosa, ofrece suficientes rojas amplias y fuera de pista para contentar a los buenos esquiadores. Alójate en cualquiera de las dos y todo el dominio se abre al otro lado de la loma.",
      pt: "La Forêt Blanche une Vars e Risoul pelo Pic de Chabrières em 185 km de pistas solarengas e ladeadas de lariços, nos Alpes do Sul. Acolhedora, de boa relação qualidade-preço e fiavelmente luminosa, oferece amplas vermelhas e fora-de-pista que chegam para contentar os bons esquiadores. Fique numa das duas e todo o domínio se abre do outro lado da crista.",
    },
  },
  {
    slug: 'galibier-thabor',
    name: 'Galibier-Thabor',
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['valloire', 'valmeinier'],
    lat: 45.17,
    lng: 6.45,
    zoom: 12,
    pistesKm: 150,
    lifts: 30,
    topAltitude: 2600,
    pass: 'Galibier-Thabor',
    intro: {
      en: 'Valloire and Valmeinier linked at the foot of the Galibier, 150 km of sunny Maurienne piste.',
      fr: "Valloire et Valmeinier reliés au pied du Galibier, 150 km de pistes ensoleillées de Maurienne.",
      es: "Valloire y Valmeinier unidos al pie del Galibier, 150 km de pistas soleadas de la Maurienne.",
      pt: "Valloire e Valmeinier ligados ao pé do Galibier, 150 km de pistas solarengas da Maurienne.",
    },
    description: {
      en: 'The Galibier-Thabor domain joins the old village of Valloire with the quieter Valmeinier for 150 km of sunny, varied piste below the legendary Col du Galibier. It mixes real Savoyard character with reliable high-altitude snow, at prices well under the Tarentaise giants. Two contrasting bases, one connected domain.',
      fr: "Le domaine Galibier-Thabor unit le vieux village de Valloire à la plus tranquille Valmeinier pour 150 km de pistes ensoleillées et variées, sous le légendaire col du Galibier. Il mêle un vrai caractère savoyard à une neige d'altitude fiable, à des tarifs bien inférieurs aux géants de Tarentaise. Deux bases contrastées, un domaine relié.",
      es: "El dominio Galibier-Thabor une el viejo pueblo de Valloire con la más tranquila Valmeinier para 150 km de pistas soleadas y variadas, bajo el legendario Col du Galibier. Mezcla un carácter saboyano de verdad con una nieve de altura fiable, a precios muy por debajo de los gigantes de la Tarentaise. Dos bases contrastadas, un dominio conectado.",
      pt: "O domínio Galibier-Thabor une a velha aldeia de Valloire à mais tranquila Valmeinier para 150 km de pistas solarengas e variadas, sob o lendário Col du Galibier. Mistura um carácter saboiano a sério com uma neve de altitude fiável, a preços bem abaixo dos gigantes da Tarentaise. Duas bases contrastantes, um domínio ligado.",
    },
  },
  {
    slug: 'grand-domaine',
    name: 'Le Grand Domaine',
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['valmorel', 'saint-francois-longchamp'],
    lat: 45.43,
    lng: 6.43,
    zoom: 12,
    pistesKm: 165,
    lifts: 49,
    topAltitude: 2550,
    pass: 'Le Grand Domaine',
    intro: {
      en: 'Valmorel and Saint-François-Longchamp linked over the Col de la Madeleine, 165 km on one pass.',
      fr: "Valmorel et Saint-François-Longchamp reliés par le col de la Madeleine, 165 km sur un seul forfait.",
      es: "Valmorel y Saint-François-Longchamp unidos por el Col de la Madeleine, 165 km con un solo forfait.",
      pt: "Valmorel e Saint-François-Longchamp ligados pelo Col de la Madeleine, 165 km num só forfait.",
    },
    description: {
      en: 'Le Grand Domaine connects Valmorel and Saint-François-Longchamp across the Col de la Madeleine into 165 km of sunny, mostly intermediate piste. It is one of the better-value family domains in the Savoie, low-key, well-laid-out and rarely crowded. Either resort gives you the whole area at the door.',
      fr: "Le Grand Domaine relie Valmorel et Saint-François-Longchamp par le col de la Madeleine en 165 km de pistes ensoleillées, surtout intermédiaires. C'est l'un des domaines familiaux au meilleur rapport qualité-prix de Savoie, discret, bien tracé et rarement bondé. Chaque station vous donne tout le domaine à la porte.",
      es: "Le Grand Domaine conecta Valmorel y Saint-François-Longchamp por el Col de la Madeleine en 165 km de pistas soleadas, sobre todo intermedias. Es uno de los dominios familiares de mejor relación calidad-precio de la Saboya, discreto, bien trazado y rara vez abarrotado. Cualquiera de las dos estaciones te da todo el dominio a la puerta.",
      pt: "Le Grand Domaine liga Valmorel e Saint-François-Longchamp pelo Col de la Madeleine em 165 km de pistas solarengas, sobretudo intermédias. É um dos domínios familiares de melhor relação qualidade-preço da Saboia, discreto, bem traçado e raramente cheio. Qualquer das duas estâncias dá-lhe todo o domínio à porta.",
    },
  },
  {
    slug: 'alpe-dhuez',
    name: "Alpe d'Huez Grand Domaine",
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['alpe-d-huez', 'vaujany'],
    lat: 45.09,
    lng: 6.07,
    zoom: 12,
    pistesKm: 250,
    lifts: 81,
    topAltitude: 3330,
    pass: "Alpe d'Huez Grand Domaine Ski",
    intro: {
      en: "250 km of sun-soaked Oisans piste from the 3330 m Pic Blanc, shared by Alpe d'Huez and Vaujany.",
      fr: "250 km de pistes gorgées de soleil de l'Oisans depuis le Pic Blanc à 3330 m, partagées par l'Alpe d'Huez et Vaujany.",
      es: "250 km de pistas bañadas de sol del Oisans desde el Pic Blanc a 3330 m, compartidas por Alpe d'Huez y Vaujany.",
      pt: "250 km de pistas cheias de sol do Oisans desde o Pic Blanc a 3330 m, partilhadas por Alpe d'Huez e Vaujany.",
    },
    description: {
      en: "The Alpe d'Huez Grand Domaine spreads 250 km of famously sunny piste across the Grandes Rousses, from the glacier runs off the 3330 m Pic Blanc to the 16 km Sarenne, the longest black run in the Alps. Buzzy Alpe d'Huez and the quiet village of Vaujany are two very different ways in. One pass, the whole massif.",
      fr: "L'Alpe d'Huez Grand Domaine déploie 250 km de pistes réputées ensoleillées sur les Grandes Rousses, des descentes glaciaires du Pic Blanc à 3330 m à la Sarenne et ses 16 km, la plus longue noire des Alpes. L'animée Alpe d'Huez et le tranquille village de Vaujany sont deux portes d'entrée bien différentes. Un forfait, tout le massif.",
      es: "El Alpe d'Huez Grand Domaine despliega 250 km de pistas famosas por su sol en las Grandes Rousses, de las bajadas glaciares del Pic Blanc a 3330 m a la Sarenne y sus 16 km, la negra más larga de los Alpes. La animada Alpe d'Huez y el tranquilo pueblo de Vaujany son dos entradas muy distintas. Un forfait, todo el macizo.",
      pt: "O Alpe d'Huez Grand Domaine desdobra 250 km de pistas famosas pelo sol nas Grandes Rousses, das descidas glaciares do Pic Blanc a 3330 m à Sarenne e os seus 16 km, a mais longa negra dos Alpes. A animada Alpe d'Huez e a tranquila aldeia de Vaujany são duas entradas bem diferentes. Um forfait, todo o maciço.",
    },
  },
  {
    slug: 'via-lattea',
    name: 'Via Lattea',
    countryCodes: ['FR', 'IT'],
    flags: ['🇫🇷', '🇮🇹'],
    members: ['montgenevre', 'sestriere'],
    lat: 44.93,
    lng: 6.83,
    zoom: 11,
    pistesKm: 400,
    lifts: 70,
    topAltitude: 2800,
    pass: 'Via Lattea (Milky Way)',
    intro: {
      en: 'The cross-border Milky Way: around 400 km linking French Montgenèvre with Italian Sestriere and the Olympic slopes.',
      fr: "La Voie lactée transfrontalière : environ 400 km reliant le français Montgenèvre à l'italienne Sestriere et aux pistes olympiques.",
      es: "La Vía Láctea transfronteriza: unos 400 km que enlazan el francés Montgenèvre con la italiana Sestriere y las pistas olímpicas.",
      pt: "A Via Láctea transfronteiriça: cerca de 400 km que ligam o francês Montgenèvre à italiana Sestriere e às pistas olímpicas.",
    },
    description: {
      en: 'The Via Lattea, or Milky Way, links Montgenèvre in France with Sestriere, Sauze d\'Oulx and the other Italian villages of the 2006 Olympics into around 400 km of sunny, high piste straddling the border. It is vast, varied and great value on the Italian side, with long descents and big views. Cross from France to Italy and back on a single pass.',
      fr: "La Via Lattea, ou Voie lactée, relie Montgenèvre en France à Sestriere, Sauze d'Oulx et aux autres villages italiens des Jeux de 2006, pour environ 400 km de pistes hautes et ensoleillées à cheval sur la frontière. Vaste, variée et d'un excellent rapport qualité-prix côté italien, elle offre de longues descentes et de grands panoramas. On passe de France en Italie et retour sur un seul forfait.",
      es: "La Via Lattea, o Vía Láctea, enlaza Montgenèvre en Francia con Sestriere, Sauze d'Oulx y los demás pueblos italianos de los Juegos de 2006, en unos 400 km de pistas altas y soleadas a caballo de la frontera. Vasta, variada y de excelente relación calidad-precio en el lado italiano, ofrece largos descensos y grandes vistas. Se pasa de Francia a Italia y vuelta con un solo forfait.",
      pt: "A Via Lattea, ou Via Láctea, liga Montgenèvre em França a Sestriere, Sauze d'Oulx e às outras aldeias italianas dos Jogos de 2006, em cerca de 400 km de pistas altas e solarengas a cavalo da fronteira. Vasta, variada e de excelente relação qualidade-preço do lado italiano, oferece longas descidas e grandes vistas. Passa-se de França para Itália e de volta num só forfait.",
    },
  },
  {
    slug: 'alp-2500',
    name: 'Alp 2500',
    countryCodes: ['ES'],
    flags: ['🇪🇸'],
    members: ['la-molina', 'masella'],
    lat: 42.35,
    lng: 1.95,
    zoom: 12,
    pistesKm: 140,
    lifts: 31,
    topAltitude: 2537,
    pass: 'Alp 2500',
    intro: {
      en: 'La Molina and Masella linked over the Tosa d\'Alp, 140 km and the largest domain in the eastern Spanish Pyrenees.',
      fr: "La Molina et Masella reliés par la Tosa d'Alp, 140 km et le plus grand domaine des Pyrénées espagnoles orientales.",
      es: "La Molina y Masella unidas por la Tosa d'Alp, 140 km y el mayor dominio del Pirineo oriental español.",
      pt: "La Molina e Masella ligadas pela Tosa d'Alp, 140 km e o maior domínio dos Pirenéus orientais espanhóis.",
    },
    description: {
      en: 'Alp 2500 joins historic La Molina with forested Masella over the 2537 m Tosa d\'Alp, making 140 km of sunny, family-friendly piste, the biggest linked area in the Catalan Pyrenees. It is easy to reach from Barcelona, even by train, and famous for long tree runs and night skiing. Two resorts, one of the friendliest big domains in Spain.',
      fr: "Alp 2500 unit l'historique La Molina à la boisée Masella par-dessus la Tosa d'Alp à 2537 m, pour 140 km de pistes ensoleillées et familiales, le plus grand domaine relié des Pyrénées catalanes. Facile d'accès depuis Barcelone, même en train, il est réputé pour ses longues pistes en forêt et son ski nocturne. Deux stations, l'un des grands domaines les plus accueillants d'Espagne.",
      es: "Alp 2500 une la histórica La Molina con la arbolada Masella por encima de la Tosa d'Alp a 2537 m, para 140 km de pistas soleadas y familiares, el mayor dominio enlazado del Pirineo catalán. Es fácil de alcanzar desde Barcelona, incluso en tren, y famoso por sus largas pistas entre árboles y su esquí nocturno. Dos estaciones, uno de los grandes dominios más acogedores de España.",
      pt: "Alp 2500 une a histórica La Molina à arborizada Masella por cima da Tosa d'Alp a 2537 m, para 140 km de pistas solarengas e familiares, o maior domínio ligado dos Pirenéus catalães. É fácil de alcançar desde Barcelona, mesmo de comboio, e famoso pelas longas pistas entre árvores e pelo esqui noturno. Duas estâncias, um dos grandes domínios mais acolhedores de Espanha.",
    },
  },
  {
    slug: 'formigal-panticosa',
    name: 'Formigal-Panticosa',
    countryCodes: ['ES'],
    flags: ['🇪🇸'],
    members: ['formigal', 'panticosa'],
    lat: 42.77,
    lng: -0.35,
    zoom: 11,
    pistesKm: 216,
    lifts: 36,
    topAltitude: 2250,
    pass: 'Aramón Formigal-Panticosa',
    intro: {
      en: "The Tena valley's two resorts on one Aramón pass: lively Formigal and scenic Panticosa, 216 km in all.",
      fr: "Les deux stations de la vallée de Tena sur un seul forfait Aramón : l'animée Formigal et la photogénique Panticosa, 216 km au total.",
      es: "Las dos estaciones del valle de Tena con un solo forfait Aramón: la animada Formigal y la pintoresca Panticosa, 216 km en total.",
      pt: "As duas estâncias do vale de Tena num só passe Aramón: a animada Formigal e a pitoresca Panticosa, 216 km no total.",
    },
    description: {
      en: 'Formigal and Panticosa sit in the Aragonese Tena valley and share a single Aramón lift pass, combining for around 216 km of piste, the largest ski offer in the Spanish Pyrenees. Big, sunny, party-loving Formigal contrasts with the smaller, prettier Panticosa and its famous spa just down the valley. One pass covers both mountains.',
      fr: "Formigal et Panticosa se situent dans la vallée aragonaise de Tena et partagent un seul forfait Aramón, soit environ 216 km de pistes au total, la plus grande offre de ski des Pyrénées espagnoles. La grande, ensoleillée et festive Formigal contraste avec la plus petite et plus jolie Panticosa et ses thermes réputés en contrebas. Un forfait couvre les deux montagnes.",
      es: "Formigal y Panticosa están en el valle aragonés de Tena y comparten un solo forfait Aramón, sumando unos 216 km de pistas, la mayor oferta de esquí del Pirineo español. La grande, soleada y fiestera Formigal contrasta con la más pequeña y bonita Panticosa y su famoso balneario valle abajo. Un forfait cubre las dos montañas.",
      pt: "Formigal e Panticosa ficam no vale aragonês de Tena e partilham um só passe Aramón, somando cerca de 216 km de pistas, a maior oferta de esqui dos Pirenéus espanhóis. A grande, solarenga e festiva Formigal contrasta com a mais pequena e bonita Panticosa e as suas famosas termas vale abaixo. Um passe cobre as duas montanhas.",
    },
  },
  {
    slug: 'vallnord',
    name: 'Vallnord',
    countryCodes: ['AD'],
    flags: ['🇦🇩'],
    members: ['vallnord-pal-arinsal', 'vallnord-ordino-arcalis'],
    lat: 42.57,
    lng: 1.5,
    zoom: 12,
    pistesKm: 93,
    lifts: 45,
    topAltitude: 2625,
    pass: 'Vallnord',
    intro: {
      en: "Andorra's western domains: family Pal-Arinsal and freeride Ordino-Arcalís, under the Vallnord name.",
      fr: "Les domaines de l'ouest andorran : la familiale Pal-Arinsal et la freeride Ordino-Arcalís, sous le nom de Vallnord.",
      es: "Los dominios del oeste andorrano: la familiar Pal-Arinsal y la freeride Ordino-Arcalís, bajo el nombre de Vallnord.",
      pt: "Os domínios do oeste andorrano: a familiar Pal-Arinsal e a freeride Ordino-Arcalís, sob o nome Vallnord.",
    },
    description: {
      en: 'Vallnord groups Andorra\'s western ski areas, the linked family slopes of Pal-Arinsal and the wilder, north-facing Ordino-Arcalís, for around 93 km of varied piste. Together they are the snowier, quieter alternative to giant Grandvalira on the other side of the country. Two distinct mountains, one Andorran name.',
      fr: "Vallnord regroupe les domaines de l'ouest andorran, les pentes familiales reliées de Pal-Arinsal et la plus sauvage Ordino-Arcalís orientée nord, pour environ 93 km de pistes variées. Ensemble, ils forment l'alternative plus enneigée et plus calme à la géante Grandvalira, de l'autre côté du pays. Deux montagnes distinctes, un nom andorran.",
      es: "Vallnord agrupa los dominios del oeste andorrano, las laderas familiares enlazadas de Pal-Arinsal y la más salvaje Ordino-Arcalís orientada al norte, para unos 93 km de pistas variadas. Juntos son la alternativa más nevada y tranquila a la gigante Grandvalira, al otro lado del país. Dos montañas distintas, un nombre andorrano.",
      pt: "Vallnord agrupa os domínios do oeste andorrano, as encostas familiares ligadas de Pal-Arinsal e a mais selvagem Ordino-Arcalís virada a norte, para cerca de 93 km de pistas variadas. Juntos são a alternativa mais nevada e tranquila à gigante Grandvalira, do outro lado do país. Duas montanhas distintas, um nome andorrano.",
    },
  },
  {
    slug: 'ski-arlberg',
    name: 'Ski Arlberg',
    countryCodes: ['AT'],
    flags: ['🇦🇹'],
    members: ['st-anton', 'lech-zurs'],
    lat: 47.13,
    lng: 10.21,
    zoom: 11,
    pistesKm: 305,
    lifts: 88,
    topAltitude: 2650,
    pass: 'Ski Arlberg',
    intro: {
      en: "Austria's largest linked domain: St. Anton and Lech-Zürs joined into 305 km, the cradle of alpine skiing.",
      fr: "Le plus grand domaine relié d'Autriche : St. Anton et Lech-Zürs réunis en 305 km, le berceau du ski alpin.",
      es: "El mayor dominio enlazado de Austria: St. Anton y Lech-Zürs unidos en 305 km, la cuna del esquí alpino.",
      pt: "O maior domínio ligado da Áustria: St. Anton e Lech-Zürs unidos em 305 km, o berço do esqui alpino.",
    },
    description: {
      en: 'Ski Arlberg links St. Anton, Lech, Zürs, Stuben and Warth-Schröcken into 305 km of piste and around 88 lifts, the biggest connected ski area in Austria and the birthplace of modern alpine technique. It pairs the legendary off-piste and nightlife of St. Anton with the chic, snow-sure bowls of Lech-Zürs, all on one pass and the famous White Ring circuit. Two of its great resorts anchor the domain here.',
      fr: "Ski Arlberg relie St. Anton, Lech, Zürs, Stuben et Warth-Schröcken en 305 km de pistes et environ 88 remontées, le plus grand domaine relié d'Autriche et le berceau de la technique alpine moderne. Il associe le hors-piste et la vie nocturne légendaires de St. Anton aux combes chics et bien enneigées de Lech-Zürs, le tout sur un forfait et le fameux circuit du White Ring. Deux de ses grandes stations ancrent le domaine ici.",
      es: "Ski Arlberg une St. Anton, Lech, Zürs, Stuben y Warth-Schröcken en 305 km de pistas y unos 88 remontes, el mayor dominio conectado de Austria y la cuna de la técnica alpina moderna. Combina el fuera de pista y la vida nocturna legendarios de St. Anton con los circos chic y de nieve segura de Lech-Zürs, todo con un forfait y el famoso circuito del White Ring. Dos de sus grandes estaciones anclan el dominio aquí.",
      pt: "Ski Arlberg une St. Anton, Lech, Zürs, Stuben e Warth-Schröcken em 305 km de pistas e cerca de 88 teleféricos, o maior domínio ligado da Áustria e o berço da técnica alpina moderna. Combina o fora-de-pista e a vida noturna lendários de St. Anton com os circos chiques e de neve segura de Lech-Zürs, tudo num passe e no famoso circuito do White Ring. Duas das suas grandes estâncias ancoram o domínio aqui.",
    },
  },
  {
    slug: 'chamonix-valley',
    name: 'Chamonix Mont-Blanc',
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['chamonix', 'les-houches'],
    lat: 45.92,
    lng: 6.87,
    zoom: 12,
    pistesKm: 170,
    lifts: 49,
    topAltitude: 3300,
    pass: 'Mont Blanc Unlimited',
    intro: {
      en: 'The legendary Mont Blanc valley: Chamonix and Les Houches and 170 km of terrain on the Mont Blanc Unlimited pass.',
      fr: "La légendaire vallée du Mont-Blanc : Chamonix et Les Houches, 170 km de terrain sur le forfait Mont Blanc Unlimited.",
      es: "El legendario valle del Mont Blanc: Chamonix y Les Houches, 170 km de terreno con el forfait Mont Blanc Unlimited.",
      pt: "O lendário vale do Mont Blanc: Chamonix e Les Houches, 170 km de terreno no passe Mont Blanc Unlimited.",
    },
    description: {
      en: 'The Chamonix valley spreads 170 km of piste across separate sectors under Mont Blanc, from the gentle, forested slopes of Les Houches to the steep, glacier-fringed terrain of the Grands Montets. The Mont Blanc Unlimited pass ties them together and reaches into Italy and Switzerland. It is as much a mountaineering capital as a ski resort, unmatched for scenery and serious off-piste.',
      fr: "La vallée de Chamonix déploie 170 km de pistes sur des secteurs séparés sous le Mont Blanc, des pentes douces et boisées des Houches au terrain raide et glaciaire des Grands Montets. Le forfait Mont Blanc Unlimited les réunit et s'étend jusqu'en Italie et en Suisse. C'est autant une capitale de l'alpinisme qu'une station de ski, sans rivale pour les paysages et le hors-piste sérieux.",
      es: "El valle de Chamonix despliega 170 km de pistas por sectores separados bajo el Mont Blanc, de las laderas suaves y arboladas de Les Houches al terreno empinado y glaciar de los Grands Montets. El forfait Mont Blanc Unlimited los une y llega hasta Italia y Suiza. Es tanto una capital del alpinismo como una estación de esquí, sin rival en paisaje y fuera de pista serio.",
      pt: "O vale de Chamonix desdobra 170 km de pistas por setores separados sob o Mont Blanc, das encostas suaves e arborizadas de Les Houches ao terreno íngreme e glaciar dos Grands Montets. O passe Mont Blanc Unlimited liga-os e estende-se até Itália e à Suíça. É tanto uma capital do alpinismo como uma estância de esqui, sem rival em paisagem e fora-de-pista a sério.",
    },
  },
  {
    slug: 'les-aravis',
    name: 'Les Aravis',
    countryCodes: ['FR'],
    flags: ['🇫🇷'],
    members: ['la-clusaz', 'le-grand-bornand'],
    lat: 45.92,
    lng: 6.45,
    zoom: 12,
    pistesKm: 220,
    lifts: 80,
    topAltitude: 2600,
    pass: 'Les Aravis',
    intro: {
      en: 'Two neighbouring Aravis resorts near Annecy, La Clusaz and Le Grand-Bornand, around 220 km between them.',
      fr: "Deux stations voisines des Aravis près d'Annecy, La Clusaz et Le Grand-Bornand, environ 220 km à elles deux.",
      es: "Dos estaciones vecinas de los Aravis cerca de Annecy, La Clusaz y Le Grand-Bornand, unos 220 km entre las dos.",
      pt: "Duas estâncias vizinhas dos Aravis perto de Annecy, La Clusaz e Le Grand-Bornand, cerca de 220 km entre as duas.",
    },
    description: {
      en: 'The Aravis massif above Annecy holds two of the most authentic resorts in the northern Alps, La Clusaz and Le Grand-Bornand, with around 220 km of sunny piste between them and a shared local pass. Both are working Savoyard villages, strong on character, food and tree-lined runs rather than high-rise convenience. Close to Geneva, they are a favourite weekend escape.',
      fr: "Le massif des Aravis au-dessus d'Annecy abrite deux des stations les plus authentiques des Alpes du Nord, La Clusaz et Le Grand-Bornand, avec environ 220 km de pistes ensoleillées à elles deux et un forfait local commun. Ce sont de vrais villages savoyards, riches en caractère, en cuisine et en pistes boisées plutôt qu'en immeubles pratiques. Proches de Genève, c'est une escapade de week-end favorite.",
      es: "El macizo de los Aravis sobre Annecy alberga dos de las estaciones más auténticas de los Alpes del Norte, La Clusaz y Le Grand-Bornand, con unos 220 km de pistas soleadas entre las dos y un forfait local compartido. Son pueblos saboyanos de verdad, fuertes en carácter, gastronomía y pistas entre árboles más que en bloques prácticos. Cerca de Ginebra, son una escapada de fin de semana favorita.",
      pt: "O maciço dos Aravis acima de Annecy alberga duas das estâncias mais autênticas dos Alpes do Norte, La Clusaz e Le Grand-Bornand, com cerca de 220 km de pistas solarengas entre as duas e um passe local partilhado. São verdadeiras aldeias saboianas, fortes em carácter, gastronomia e pistas entre árvores mais do que em blocos práticos. Perto de Genebra, são uma escapadela de fim de semana favorita.",
    },
  },
]

export function getSkiArea(slug: string): SkiArea | undefined {
  return SKI_AREAS.find((a) => a.slug === slug)
}

/** The ski area a resort belongs to, if any (used for the resort-page cross-link). */
export function getSkiAreaForResort(resortSlug: string): SkiArea | undefined {
  return SKI_AREAS.find((a) => a.members.includes(resortSlug))
}
