import type { Locale } from '@/app/[locale]/dictionaries'

/**
 * Localised vibe labels shown as chips on cards and destination pages.
 * Source slugs live in data/destinations.json. Industry terms that natives
 * use as-is (freeride, freestyle, boutique, Skicircus, Sellaronda) and proper
 * nouns are kept untranslated on purpose, exactly as a local writer would.
 */
const VIBES: Record<string, Record<Locale, string>> = {
  'high-altitude': { en: 'high altitude', fr: 'haute altitude', es: 'alta altitud', pt: 'alta altitude', it: 'alta quota', nl: 'grote hoogte' },
  party: { en: 'party', fr: 'fête', es: 'fiesta', pt: 'festa', it: 'festa', nl: 'feest' },
  freeride: { en: 'freeride', fr: 'freeride', es: 'freeride', pt: 'freeride', it: 'freeride', nl: 'freeride' },
  luxury: { en: 'luxury', fr: 'luxe', es: 'lujo', pt: 'luxo', it: 'lusso', nl: 'luxe' },
  racing: { en: 'racing', fr: 'compétition', es: 'competición', pt: 'competição', it: 'agonismo', nl: 'competitie' },
  family: { en: 'family', fr: 'famille', es: 'familia', pt: 'família', it: 'famiglia', nl: 'familie' },
  gastronomy: { en: 'gastronomy', fr: 'gastronomie', es: 'gastronomía', pt: 'gastronomia', it: 'gastronomia', nl: 'gastronomie' },
  chalet: { en: 'chalet', fr: 'chalet', es: 'chalet', pt: 'chalé', it: 'chalet', nl: 'chalet' },
  'british-friendly': { en: 'British-friendly', fr: 'public britannique', es: 'público británico', pt: 'público britânico', it: 'pubblico britannico', nl: 'Brits publiek' },
  mountaineering: { en: 'mountaineering', fr: 'alpinisme', es: 'alpinismo', pt: 'alpinismo', it: 'alpinismo', nl: 'alpinisme' },
  iconic: { en: 'iconic', fr: 'emblématique', es: 'icónico', pt: 'icónico', it: 'iconica', nl: 'iconisch' },
  value: { en: 'value', fr: 'bon plan', es: 'buena relación', pt: 'boa relação', it: 'ottimo prezzo', nl: 'prijs-kwaliteit' },
  glacier: { en: 'glacier', fr: 'glacier', es: 'glaciar', pt: 'glaciar', it: 'ghiacciaio', nl: 'gletsjer' },
  sunny: { en: 'sunny', fr: 'ensoleillé', es: 'soleado', pt: 'solarengo', it: 'soleggiata', nl: 'zonnig' },
  authentic: { en: 'authentic', fr: 'authentique', es: 'auténtico', pt: 'autêntico', it: 'autentica', nl: 'authentiek' },
  'tree-skiing': { en: 'tree skiing', fr: 'ski en forêt', es: 'esquí en bosque', pt: 'esqui em floresta', it: 'sci nei boschi', nl: 'bosskiën' },
  thermal: { en: 'thermal', fr: 'thermal', es: 'termal', pt: 'termal', it: 'terme', nl: 'thermaal' },
  'winter-sports': { en: 'winter sports', fr: 'sports d\'hiver', es: 'deportes de invierno', pt: 'desportos de inverno', it: 'sport invernali', nl: 'wintersport' },
  'car-free': { en: 'car-free', fr: 'sans voitures', es: 'sin coches', pt: 'sem carros', it: 'senza auto', nl: 'autovrij' },
  'summer-ski': { en: 'summer skiing', fr: 'ski d\'été', es: 'esquí de verano', pt: 'esqui de verão', it: 'sci estivo', nl: 'zomerskiën' },
  'big-domain': { en: 'big domain', fr: 'grand domaine', es: 'gran dominio', pt: 'grande domínio', it: 'grande comprensorio', nl: 'groot skigebied' },
  wellness: { en: 'wellness', fr: 'bien-être', es: 'bienestar', pt: 'bem-estar', it: 'benessere', nl: 'wellness' },
  expert: { en: 'expert', fr: 'expert', es: 'experto', pt: 'experto', it: 'esperti', nl: 'expert' },
  concerts: { en: 'concerts', fr: 'concerts', es: 'conciertos', pt: 'concertos', it: 'concerti', nl: 'concerten' },
  'duty-free': { en: 'duty-free', fr: 'détaxé', es: 'libre de impuestos', pt: 'isento de impostos', it: 'duty-free', nl: 'belastingvrij' },
  freestyle: { en: 'freestyle', fr: 'freestyle', es: 'freestyle', pt: 'freestyle', it: 'freestyle', nl: 'freestyle' },
  historic: { en: 'historic', fr: 'historique', es: 'histórico', pt: 'histórico', it: 'storica', nl: 'historisch' },
  'old-money': { en: 'old money', fr: 'chic discret', es: 'lujo clásico', pt: 'luxo clássico', it: 'eleganza discreta', nl: 'ingetogen chic' },
  skicircus: { en: 'Skicircus', fr: 'Skicircus', es: 'Skicircus', pt: 'Skicircus', it: 'Skicircus', nl: 'Skicircus' },
  'snow-sure': { en: 'snow-sure', fr: 'enneigement garanti', es: 'nieve garantizada', pt: 'neve garantida', it: 'neve sicura', nl: 'sneeuwzekerheid' },
  discreet: { en: 'discreet', fr: 'discret', es: 'discreto', pt: 'discreto', it: 'discreta', nl: 'discreet' },
  dolomites: { en: 'Dolomites', fr: 'Dolomites', es: 'Dolomitas', pt: 'Dolomitas', it: 'Dolomiti', nl: 'Dolomieten' },
  scenic: { en: 'scenic', fr: 'panoramique', es: 'panorámico', pt: 'panorâmico', it: 'panoramica', nl: 'panoramisch' },
  'cross-border': { en: 'cross-border', fr: 'transfrontalier', es: 'transfronterizo', pt: 'transfronteiriço', it: 'transfrontaliera', nl: 'grensoverschrijdend' },
  elegance: { en: 'elegance', fr: 'élégance', es: 'elegancia', pt: 'elegância', it: 'eleganza', nl: 'elegantie' },
  italian: { en: 'Italian', fr: 'à l\'italienne', es: 'a la italiana', pt: 'à italiana', it: 'all\'italiana', nl: 'op Italiaanse wijze' },
  habsburg: { en: 'Habsburg', fr: 'Habsbourg', es: 'Habsburgo', pt: 'Habsburgo', it: 'Asburgo', nl: 'Habsburgs' },
  'milky-way': { en: 'Milky Way', fr: 'Voie lactée', es: 'Vía láctea', pt: 'Via láctea', it: 'Via Lattea', nl: 'Melkweg' },
  'dolomiti-superski': { en: 'Dolomiti Superski', fr: 'Dolomiti Superski', es: 'Dolomiti Superski', pt: 'Dolomiti Superski', it: 'Dolomiti Superski', nl: 'Dolomiti Superski' },
  sellaronda: { en: 'Sellaronda', fr: 'Sellaronda', es: 'Sellaronda', pt: 'Sellaronda', it: 'Sellaronda', nl: 'Sellaronda' },
  panoramic: { en: 'panoramic', fr: 'panoramique', es: 'panorámico', pt: 'panorâmico', it: 'panoramica', nl: 'panoramisch' },
  'luxury-iberian': { en: 'Iberian luxury', fr: 'luxe ibérique', es: 'lujo ibérico', pt: 'luxo ibérico', it: 'lusso iberico', nl: 'Iberische luxe' },
  royal: { en: 'royal', fr: 'royal', es: 'real', pt: 'real', it: 'reale', nl: 'koninklijk' },
  village: { en: 'village', fr: 'village', es: 'pueblo', pt: 'aldeia', it: 'borgo', nl: 'dorp' },
  altitude: { en: 'altitude', fr: 'altitude', es: 'altitud', pt: 'altitude', it: 'quota', nl: 'hoogte' },
  'young-crowd': { en: 'young crowd', fr: 'public jeune', es: 'público joven', pt: 'público jovem', it: 'pubblico giovane', nl: 'jong publiek' },
  beginner: { en: 'beginner', fr: 'débutant', es: 'principiante', pt: 'principiante', it: 'principianti', nl: 'beginners' },
  'altitude-pyrenees': { en: 'high Pyrenees', fr: 'Pyrénées d\'altitude', es: 'Pirineos en altitud', pt: 'Pirenéus em altitude', it: 'Pirenei in quota', nl: 'hoog in de Pyreneeën' },
  sunshine: { en: 'sunshine', fr: 'soleil', es: 'sol', pt: 'sol', it: 'sole', nl: 'zon' },
  'altitude-training': { en: 'altitude training', fr: 'entraînement en altitude', es: 'entrenamiento en altitud', pt: 'treino em altitude', it: 'allenamento in quota', nl: 'hoogtetraining' },
  'pyrenees-grand': { en: 'grand Pyrenees', fr: 'grandes Pyrénées', es: 'grandes Pirineos', pt: 'grandes Pirenéus', it: 'grandi Pirenei', nl: 'grote Pyreneeën' },
  'cycling-meets-ski': { en: 'cycling meets ski', fr: 'vélo et ski', es: 'ciclismo y esquí', pt: 'ciclismo e esqui', it: 'ciclismo e sci', nl: 'wielrennen en ski' },
  'thermal-belle-epoque': { en: 'Belle Époque spa', fr: 'thermal Belle Époque', es: 'termal Belle Époque', pt: 'termal Belle Époque', it: 'terme Belle Époque', nl: 'thermaal Belle Époque' },
  'national-park': { en: 'national park', fr: 'parc national', es: 'parque nacional', pt: 'parque nacional', it: 'parco nazionale', nl: 'nationaal park' },
  boutique: { en: 'boutique', fr: 'boutique', es: 'boutique', pt: 'boutique', it: 'boutique', nl: 'boutique' },
  renaissance: { en: 'renaissance', fr: 'renaissance', es: 'renacimiento', pt: 'renascimento', it: 'rinascita', nl: 'renaissance' },
  japow: { en: 'japow', fr: 'japow', es: 'japow', pt: 'japow', it: 'japow', nl: 'japow' },
  onsen: { en: 'onsen', fr: 'onsen', es: 'onsen', pt: 'onsen', it: 'onsen', nl: 'onsen' },
  traditional: { en: 'traditional', fr: 'traditionnel', es: 'tradicional', pt: 'tradicional', it: 'tradizionale', nl: 'traditioneel' },
  'big-mountain': { en: 'big mountain', fr: 'grande montagne', es: 'gran montaña', pt: 'grande montanha', it: 'grande montagna', nl: 'grote berg' },
  olympic: { en: 'Olympic', fr: 'olympique', es: 'olímpico', pt: 'olímpico', it: 'olimpico', nl: 'olympisch' },
  'city-access': { en: 'city access', fr: "à un pas de la ville", es: 'acceso urbano', pt: 'acesso urbano', it: 'a un passo dalla città', nl: 'dicht bij de stad' },
  'snow-monsters': { en: 'snow monsters', fr: 'monstres de neige', es: 'monstruos de nieve', pt: 'monstros de neve', it: 'mostri di neve', nl: 'sneeuwmonsters' },
  'ice-village': { en: 'ice village', fr: 'village de glace', es: 'aldea de hielo', pt: 'aldeia de gelo', it: 'villaggio di ghiaccio', nl: 'ijsdorp' },
  'back-bowls': { en: 'back bowls', fr: 'bowls de poudreuse', es: 'cuencos de polvo', pt: 'bowls de neve', it: 'conche di polvere', nl: 'poederkommen' },
  powder: { en: 'powder', fr: 'poudreuse', es: 'nieve polvo', pt: 'neve em pó', it: 'neve fresca', nl: 'poedersneeuw' },
  'east-coast': { en: 'East Coast', fr: 'côte Est', es: 'costa Este', pt: 'costa Leste', it: 'costa orientale', nl: 'oostkust' },
  charming: { en: 'charming', fr: 'charmant', es: 'con encanto', pt: 'encantador', it: 'incantevole', nl: 'charmant' },
  vintage: { en: 'vintage', fr: 'rétro chic', es: 'vintage', pt: 'vintage', it: 'vintage', nl: 'vintage' },
  tram: { en: 'tram-access', fr: 'téléphérique-roi', es: 'teleférico estrella', pt: 'teleférico ícone', it: 'funivia regina', nl: 'iconische lift' },
  isolated: { en: 'isolated', fr: 'isolée', es: 'aislada', pt: 'isolada', it: 'isolata', nl: 'afgelegen' },
  'ski-only': { en: 'ski-only', fr: 'skis seulement', es: 'solo esquí', pt: 'só esqui', it: 'solo sci', nl: 'alleen skiën' },
  'desert-ski': { en: 'desert ski', fr: 'ski du désert', es: 'esquí del desierto', pt: 'esqui do deserto', it: 'sci del deserto', nl: 'woestijnskiën' },
  'cedar-forest': { en: 'cedar forest', fr: 'cédraie', es: 'cedral', pt: 'cedral', it: 'cedrate', nl: 'cederbos' },
  'southern-hemisphere': { en: 'Southern Hemisphere', fr: 'hémisphère sud', es: 'hemisferio sur', pt: 'hemisfério sul', it: 'emisfero sud', nl: 'zuidelijk halfrond' },
  volcano: { en: 'volcano', fr: 'volcan', es: 'volcán', pt: 'vulcão', it: 'vulcano', nl: 'vulkaan' },
  indoor: { en: 'indoor', fr: 'indoor', es: 'cubierto', pt: 'indoor', it: 'indoor', nl: 'indoor' },
  'year-round': { en: 'year-round', fr: "toute l'année", es: 'todo el año', pt: 'todo o ano', it: 'tutto l\'anno', nl: 'het hele jaar' },
  unique: { en: 'unique', fr: 'unique', es: 'único', pt: 'único', it: 'unica', nl: 'uniek' },
  'night-ski': { en: 'night skiing', fr: 'ski nocturne', es: 'esquí nocturno', pt: 'esqui noturno', it: 'sci notturno', nl: 'nachtskiën' },
}

export function localizeVibe(slug: string, locale: Locale): string {
  const entry = VIBES[slug]
  if (entry) return entry[locale]
  // Fallback: turn the slug into a readable label.
  return slug.replace(/-/g, ' ')
}
